# Generated by Django 4.2.16 on 2024-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_field', models.JSONField(default=list)),
                ('computer_field', models.JSONField(default=list)),
                ('player_shots', models.JSONField(default=list)),
                ('computer_shots', models.JSONField(default=list)),
                ('is_player_turn', models.BooleanField(default=True)),
                ('game_over', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
