# Generated by Django 4.2.16 on 2024-10-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AlterField(
            model_name='game',
            name='computer_field',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='computer_shots',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_field',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_shots',
            field=models.JSONField(),
        ),
    ]
