# Generated by Django 4.2.16 on 2024-10-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_winner_alter_game_computer_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hits',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='computer_field',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='computer_shots',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_field',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_shots',
            field=models.JSONField(default=list),
        ),
    ]
